# Generated by Django 4.0.1 on 2023-01-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='job_status',
            new_name='design_status',
        ),
    ]
